### ISSUE TITLE
cpufeature causes core dump in some systems

### ISSUE THREAD

**Issue by drfinkus** [robbmcleod/cpufeature#3]
See here for a more in-depth discussion: https://github.com/microsoft/DeepSpeed/issues/425#issuecomment-697808802

Can confirm the following behavior:
```
(env) user@desktop:~/code/DeepSpeed$ python -c "import cpufeature; cpufeature.print_features()"
Floating point exception (core dumped)
```

CPU: AMD Threadripper 1920x

**Comment by robbmcleod** [comment]
Well I don't have such a CPU available for testing so I'm not able to fix the problem.

**Comment by drfinkus** [comment]
OK, I am happy to help if you want any support with testing it. Just let me know.

**Comment by drfinkus** [comment]
@robbmcleod I managed to trace the error to https://github.com/robbmcleod/cpufeature/blob/254cc6129e87b5bbc6f3dfc60dbff774abb22a16/cpufeature/cpu_x86.c#L92

```
    // I'm not sure if it's possible to count physical processors in this way 
    // for 2,4 CPU machines, as there it's usually better to have one process
    // per physical CPU in my experience...
    this_x86->num_threads_per_core = info0[1] & 0xFFFF;
```
This line raises SIGFPE, Arithmetic exception.

Do you have any suggestions how to fix this? I'm happy to help debug!

**Comment by robbmcleod** [comment]
I would start by inserting print statements to see what `info0[1]` and `info1[1]` actually are as integers, since it sounds like the bit-operation is causing some arithmetic error.

What we need to find is the AMD documentation for `cpuid`. The Intel docs are here:

https://software.intel.com/content/www/us/en/develop/articles/intel-sdm.html

I'm guessing that is this AMD document:

https://www.amd.com/system/files/TechDocs/54945_3.03_ppr_ZP_B2_pub.zip

`cpuid` is documented starting on p.58. So possibly the returned values are different between the two vendors, and we would need to branch on the vendor before grabbing these values.

**Comment by drfinkus** [comment]
I added the following statements in the `detect_cores` function:
```
    printf( "x0B,0x00: Processors: %d, %d, %d, %d\n", info0[0], info0[1], info0[2], info0[3]);
    printf( "x0B,0x01: Cores:      %d, %d, %d, %d\n", info1[0], info1[1], info1[2], info1[3]);
```
The output is:
```
x0B,0x00: Processors: 0, 0, 0, 0
x0B,0x01: Cores:      0, 0, 0, 0
```

**Comment by drfinkus** [comment]
Fixed it, will issue a PR so you can take a look at it! Used the strategy you outlined above, testing for vendor and then using an AMD specific approach. Will leave this open until you take a look at the PR!

**Comment by robbmcleod** [comment]
For some unknown reason Travis CI is not getting push/pull notifications.

**Comment by robbmcleod** [comment]
Apparently Travis doesn't support Python for OSX anymore in a substantive way. So they're out. And given the long-standing issues with Appveyor not supporting new Python versions in a timely manner I think it's time for something different. I tried setting up a Github Actions setup but none of the workflows seem to trigger for some unknown reason. As usual the lack of error messages in CI is a bit maddening. I'll probably have to create some "Hello github actions" repo and work through step-by-step until I get something working.

**Comment by robbmcleod** [comment]
Would like to make use of manylinux Docker images to build wheels, so that we can have all pre-built wheels on pypi:

https://github.com/pypa/manylinux

Kivy has a full setup for both test and building wheels (but it's a might bit complicated):

https://github.com/kivy/kivy/tree/master/.github/workflows

This one builds Cython in particular but uses a custom Docker image (I would rather use the official PyPa ones):

https://github.com/marketplace/actions/python-wheels-manylinux-build
https://github.com/RalfG/python-wheels-manylinux-build

**Comment by robbmcleod** [comment]
Since this is fixed I'm going to close this issue and open a new one regarding CI tests and building wheels. Thanks for your help @drfinkus.
